// import type { Metadata } from "next";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className="bg-gray-100 text-gray-800">
            <Header/>
            <main className="container mx-auto px-4 py-8">{children}</main>
            <Footer/>
      </body>
      </html>
  );
}