// import type { Metadata } from "next";
import "../styles/globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="ko">
        <body className="text-gray-800">
            <Header/>
            <main className="container mx-auto min-h-screen max-w-3xl">{children}</main>
            <Footer/>
        </body>
      </html>
  );
}